### ISSUE TITLE
ライセンス

### ISSUE THREAD

**Issue by s3-odara** [GIZMODO-WOODS/gizmodo-woods.github.io#1]
ライセンスがないリポジトリは著作権法の保護を完全に受けてしまって、複数人での編集が法的にグレーになる上にオープンな利用がしづらくなるので自由なライセンスを付けて利用を許諾したほうがいいと思います。

**Comment by RuinDig** [comment]
あー、なるほど、そういう影響があるのか
CC-BY-4.0にしようかな

**Comment by s3-odara** [comment]
いいと思います。2023/06/03 19:58、RuinDig ***@***.***>のメール:﻿
あー、なるほど、そういう影響があるのか
CC-BY-4.0にしようかな

**Comment by RuinDig** [comment]
CC-BY-4.0ライセンスを設定

https://github.com/GIZMODO-WOODS/gizmodo-woods.github.io/blob/main/LICENSE.txt
